[toolchain]
anchor_version = "0.32.1"

[features]
resolution = true
skip-lint = false

[programs.localnet]
permission_protocol = "AtVhWaetjy4n2X7v68DnjFmkWdoRhNGqcfvtoBJJMd1Z"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "echo test"