[toolchain]
anchor_version = "0.32.1"

[features]
resolution = true
skip-lint = false

[programs.devnet]
permission_protocol = "EvnqmkfMXN3sepqFkQTQjQgWKK9XKkGe2Zou9XSWVufh"
tokenization_case = "6VF97rmPyhMgqkEQGhGu7dSm7oq9tWHZELSKqttUB4Ed"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "echo test"